api_p12_file     = ""                        // Path for p12 file downloaded from VoltConsole
api_url          = ""                        // API URL for your tenant
healthcheck_name = "healthcheck"             // Name of Health Check  
myns             = "namespace"               // Name of your namespace
op_name          = "originpool"              // Name of Origin Pool
pool_port        = "80"                      // Port Number
service_name     = "svc.namespace"           // Service Name
vsite_name       = "vsite"                   // Name of Virtual Site
httplb_name      = "httplb"                  // Name of HTTP LoadBalancer
mydomain         = ["host.namespace.domain"] // Domain name to be exposed